name: DVC CI/CD Pipeline

on:
  push:
    branches:
      - main  # This triggers the pipeline when you push to the main branch
  pull_request:
    branches:
      - main  # Trigger for pull requests to the main branch

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc  # Install DVC
          pip install dvc-azure  # Install the Azure plugin
      - name: Set up DVC remote for AZURE
        run: |
          dvc remote add -d azureremote azure://mlops
          dvc remote modify azureremote account_name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          dvc remote modify azureremote account_key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
      - name: Pull DVC data from remote
        run: |
          dvc pull  # Pull data from remote storage

      - name: Run model training (or any other task)
        run: |
          python src/model.py  
